### ISSUE TITLE
Add device type per server

### ISSUE THREAD

**Issue by mgrzybek** [mgrzybek/ansible-openvpn-gateway#2]
A parameter to specify the device type should be added. For example:
```yaml
openvpn_gateway_connections:
- name: conn
   servers:
   - server: my-endpoint.org
      port: 443
      protocol: tcp
      device: tap # <-----
```
